---
title: "Quiz3"
author: "Sabin Khadka"
date: "October 12, 2015"
output: html_document
---

```{r}
library("AppliedPredictiveModeling")
library("caret")
library("ElemStatLearn")
library("pgmm")
library("rpart")
library("rattle")
library("ggplot2")
```

Q1:

```{r, echo=FALSE}
data(segmentationOriginal)
set.seed(125)
inTrain <- createDataPartition(y = segmentationOriginal$Case, list = FALSE)
train = subset(segmentationOriginal, Case=="Train")
test = subset(segmentationOriginal, Case=="Test")
modelFit <- train(Class ~ ., data = train, method = "rpart")
modelFit$finalModel
fancyRpartPlot(modelFit$finalModel)
```

Q3:

```{r chunk2}
data(olive)
olive = olive[,-1]
model<-train(Area ~ ., data=olive, method="rpart")
newdata = as.data.frame(t(colMeans(olive)))
predict(model, newdata)
```

Q4:

```{r chunk3}
data(SAheart)
set.seed(8484)
train = sample(1:dim(SAheart)[1],size=dim(SAheart)[1]/2,replace=F)
trainSA = SAheart[train,]
testSA = SAheart[-train,]
set.seed(1234)
model <- train(chd~age+alcohol+obesity+tobacco+typea+ldl,data=trainSA,method="glm",family="binomial")
missClass <- function(values,prediction){sum(((prediction > 0.5)*1) != values)/length(values)}

missClass(trainSA$chd, predict(model, trainSA))
missClass(testSA$chd, predict(model, testSA))
```

Q5:

```{r chunk4}
library(randomForest)
data(vowel.train)
data(vowel.test)
set.seed(33833)
vowel.train$y <- factor(vowel.train$y)
vowel.test$y <- factor(vowel.test$y)

model <- randomForest(y ~ ., data = vowel.train, importance = FALSE)
var <- varImp(model)
order(var)
```
